### ISSUE TITLE
inconsistency with notification bar

### ISSUE THREAD

**Issue by Neerajrawat123** [Neerajrawat123/chat-app#1]
when a user is typing it will show to other but not wise-verse.
![Screenshot_27-8-2024_10122_localhost](https://github.com/user-attachments/assets/b39b347f-126d-4450-be08-7f3581d52284)

**Comment by Vishnu-0609** [comment]
you should pass chatid in socket.emit so whenever this event occurs it first of all checks current chatid with the chatid that received from socket you can resolve it very easily.

**Comment by Neerajrawat123** [comment]
it is the issue but not the main problem.
I will explain ' when first user typing to user second it's working fine but when the second user is typing it is not working.
Although the client socket emit the event with data { typing indicator and userid } to server .
But server not emitting the event or second client is not receiving the event.
